name : CI Practice
on : push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v4

      - name:  Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Package Json
        run: |
            npm init -y
      - name:  Install Package-lock.json
        run: |
            npm install
      
      - name: Install Dependencies
        run: npm ci

      - name: Print Information
        run: |
            echo "Runner OS: $RUNNER_OS"
            echo "Workflow : $GITHUB_WORKFLOW"
            echo "Event name : $GITHUB_EVENT_NAME"
            echo  "$${{github.job}}"
